spring: 
   datasource: 
             url: jdbc:postgresql://localhost:5432/Employee
             username: postgres
             password: System
             driver-class-name: org.postgresql.Driver
   hibernate: 
   jpa:
             show-sql: true

management:
      endpoints:
        web:
          exposure:
            include: '*'
  
server:
  port: 8082